#!/bin/sh

for i in 1 2 3    #add new values here depending on N amount of robots

 do 

  echo $i &

  rosrun lasmulticontrol3 dataprocessingnode_N.py "$i" &

  rosrun lasmulticontrol3 controller_N_est.py "$i" &

 done


