#!/bin/sh

#REMEMBER to set the proper amount of N within N_nexus.launch and add the new spawn robots in N_world.launch

for i in 1 2 3 4    #add new values here depending on N amount of robots

 do 

  echo $i &

  rosrun lasmulticontrol4 dataprocessingnode_N.py "$i" &

  rosrun lasmulticontrol4 controller_N.py "$i" &

 done

