#!/bin/sh

#REMEMBER TO SET THE PROPER AMOUNT OF N WITHIN N_nexus.launch and add the new spawn robots in N_world.launch

roslaunch lasmultigazebo3 N_nexus.launch&

sleep 5

roslaunch lasmultigazebo3 N_world.launch
