#Configuration for robot odometry EKF
#
obstacle_range: 3.0
raytrace_range: 3.0
footprint: [[-0.85, -0.85], [-0.85, 0.85], [0.85, 0.85], [0.85, 0.0], [0.85, -0.85]]
# robot_radius: 0.9

plugins:
      - {name: static_layer,           type: "costmap_2d::StaticLayer"}
      - {name: obstacles_layer,        type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}


obstacles_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: n_4hokuyo_frame, data_type: LaserScan, topic: /n_4scan, marking: true, clearing: true}

static_layer: 
  map_topic: /map
  subscribe_to_updates: true

inflation_layer:
  inflation_radius: 0.9
  cost_scaling_factor: 1.0
