#Configuration for local costmap
#
local_costmap:
  global_frame: map
  robot_base_frame: n_2/carrot2 # n_2base_footprint n_2/carrot2
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
