#!/bin/sh

rosrun lasmulticontrol4 dataprocessingnode_1_version2.py&
rosrun lasmulticontrol4 dataprocessingnode_2_version2.py&
rosrun lasmulticontrol4 dataprocessingnode_3_version2.py&
rosrun lasmulticontrol4 dataprocessingnode_4_version2.py
