#!/bin/sh

rosrun lasmulticontrol4 dataprocessingnode_1_version7.py&
rosrun lasmulticontrol4 dataprocessingnode_2_version7.py&
rosrun lasmulticontrol4 dataprocessingnode_3_version7.py&
rosrun lasmulticontrol4 dataprocessingnode_4_version7.py
