#Configuration for robot odometry EKF
#
obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[-0.4, -0.4], [-0.4, 0.4], [0.4, 0.4], [0.51, 0.0], [0.4, -0.4]]
robot_radius: 1.0
inflation_radius: 0.1

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: n_3hokuyo_frame, data_type: LaserScan, topic: /n_3scan, marking: true, clearing: true}

