#Configuration for global costmap
#
global_costmap:
  global_frame: map
  robot_base_frame: n_3/carrot3 # n_3/carrot3 # n_3base_footprint
  update_frequency: 5.0
  static_map: true
  width: 40.0 
  height: 40.0 
  origin_x: -20.0 
  origin_y: -20.0
