#Configuration for global costmap
#
global_costmap:
  global_frame: n_1/odom
  robot_base_frame: n_1/carrot1
  update_frequency: 5.0
  static_map: false
  width: 40.0 
  height: 40.0 
  origin_x: -20.0 
  origin_y: -20.0
