#Configuration for robot odometry EKF
#
obstacle_range: 0.3
raytrace_range: 0.3
footprint: [[-0.31, -0.25], [-0.31, 1.0], [1.0, 1.0], [1.11, 0.625], [1.0, -0.25]]
#robot_radius: ir_of_robot
inflation_radius: 0.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: n_1hokuyo_frame, data_type: LaserScan, topic: /n_1hokuyo_points, marking: true, clearing: true}

