#Configuration for robot odometry EKF
#
obstacle_range: 4.0
raytrace_range: 5.0
# footprint: [[-0.31, -0.25], [-0.31, 1.0], [1.0, 1.0], [1.11, 0.625], [1.0, -0.25]]
robot_radius: 0.8
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: carrot1, data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true}

