#Configuration for robot odometry EKF
#
obstacle_range: 6.0
raytrace_range: 7.0
footprint: [[-0.8, -0.8], [-0.8, 0.8], [0.8, 0.8], [1.1, 0.0], [0.8, -0.8]]
# robot_radius: 1.0
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: n_1/carrot1, data_type: LaserScan, topic: /scan_multi, marking: true, clearing: true}

